package com.muteShop.dataobject;

public class ItemSalesDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_sales.id
     *
     * @mbg.generated Thu Mar 14 12:03:12 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_sales.sales
     *
     * @mbg.generated Thu Mar 14 12:03:12 CST 2019
     */
    private Integer sales;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_sales.item_id
     *
     * @mbg.generated Thu Mar 14 12:03:12 CST 2019
     */
    private Integer itemId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_sales.id
     *
     * @return the value of item_sales.id
     *
     * @mbg.generated Thu Mar 14 12:03:12 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_sales.id
     *
     * @param id the value for item_sales.id
     *
     * @mbg.generated Thu Mar 14 12:03:12 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_sales.sales
     *
     * @return the value of item_sales.sales
     *
     * @mbg.generated Thu Mar 14 12:03:12 CST 2019
     */
    public Integer getSales() {
        return sales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_sales.sales
     *
     * @param sales the value for item_sales.sales
     *
     * @mbg.generated Thu Mar 14 12:03:12 CST 2019
     */
    public void setSales(Integer sales) {
        this.sales = sales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_sales.item_id
     *
     * @return the value of item_sales.item_id
     *
     * @mbg.generated Thu Mar 14 12:03:12 CST 2019
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_sales.item_id
     *
     * @param itemId the value for item_sales.item_id
     *
     * @mbg.generated Thu Mar 14 12:03:12 CST 2019
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }
}